type: 'byol'
project_name: 'byol'

model:
    architecture: 'resnet18'


projection_head:
    mlp_hidden_size: 256
    projection_size: 100 

train:
    n_epochs: 100
    opt: 'sgd'
data:
    mu: 0
    sig: 1

linear:
    n_epochs: 40
    lr: 0.0005
    batch_size: 50

eval:
    mu: 0
    sig: 1

###############################
### optimisable hyperparams ###
###############################
cut_threshold: 19
center_crop_size: 85
random_crop_min: 0.3
random_crop_max: 1

lr: 0.03
batch_size: 256 
momentum: 0.9
weight_decay: 0.0000005
lars: False

m: 0.996
