type: 'byol'
project_name: 'byol'

model:
    architecture: 'resnet18'

projection_head:
    mlp_hidden_size: 256
    projection_size: 100 
train:
    n_epochs: 3 
    opt: 'sgd'

data:
    mu: 0
    sig: 1

linear_model:
    n_epochs: 3
    lr: 0.0005

eval:
    mu: 0
    sig: 1

###############################
### optimisable hyperparams ###
###############################
cut_threshold: 17
center_crop_size: 90

lr: 0.2
batch_size: 256 
momentum: 0.9
weight_decay: 0.0000005

m: 0.996
