type: 'byol'
project_name: 'byol'
dataset: 'rgz'
compute: 'gpu'

model:
    arch: 'resnet18' 
    features: 512

projection_head:
    mlp_hidden_size: 256
    projection_size: 100 

train:
    n_epochs: 150
    opt: 'sgd'

data:
    color_channels: None
    classes: None
    mu: 0
    sig: 1

linear:
    n_epochs: 150
    lr: 0.0005
    batch_size: 50
    momentum: 0.9
    weight_decay: 0

eval:
    mu: 0
    sig: 1

pca:
    n_dim: 100
    n_epochs: 5
    batch_size: 10000

###############################
### optimisable hyperparams ###
###############################

## DATA ## 
cut_threshold: 20

## AUGMENTATIONS ##
center_crop_size: 85
random_crop: !!python/tuple [0.3, 1]
blur_kernel: 23 # Odd non-integer number
blur_sig: !!python/tuple [0.1, 2.0]
#blur_sig: !!python/tuple [!!python/tuple [0.1, 2.0]]
p_blur: 0.5
s: 1

## Optimiser ## 
# Base settings
lr: 0.03
batch_size: 256 
momentum: 0
weight_decay: 0.00000
# Scheduler
scheduler: None # [None, 'cosine', 'warmupcosine']
warmup_epochs: 10  # Only used in linear warmup cosine annealing

# LARS
lars: False
trust_coef: 0.003

## BYOL ## 
m: 0.996
m_decay: False
