preset: null
model:
    architecture: 'resnet18' 
    features: 512     # Number of encoded features (None just uses original resnet output)
    n_epochs: 250
    downscale: False

projection_head:
    hidden: 1024
    out: 256

data:
    color_channels: 1
    classes: 2
    input_height: 85
    rotate: True

linear:
    n_epochs: 100
    opt: 'adam'
    lr: 0.2
    batch_size: 25
    momentum: 0.9
    weight_decay: 0
    scheduler: 'cosine'


knn:
  neighbors: 20
  temperature: 0.1

## DATA ## 
cut_threshold: 19 

## AUGMENTATIONS ##
aug_type: 'simclr' # ['simclr', 'astroaug']
center_crop_size: 85
random_crop_scale: !!python/tuple [0.3, 1]
blur_kernel: 9 # Odd non-integer number
blur_sig: !!python/tuple [0.1, 2.0]
p_blur: 0.5
s: 0.5
p_grayscale: 1
p_aug: 0.5

## Optimiser ## 
# Base settings
lr: 0.06
momentum: 0.9
weight_decay: 0.0005
batch_size: 256
opt: 'sgd'
# Scheduler
scheduler: 'cosine' # ['none', 'cosine', 'warmupcosine']
warmup_epochs: 10  # Only used in linear warmup cosine annealing

# LARS
lars: False
trust_coef: 0.003
