type: 'byol'
project_name: 'debug-byol'
dataset: 'stl10' # ['imagenette', 'rgz', 'gzmnist', 'gz2', 'stl10', 'cifar10']
compute: 'slurm'
seed: 0
n_iterations: 1
debug: False
checkpoint_mode: 'last'
early_stopping: False
precision: 16 # [16, 32, 'bf16'], often overriden
topk: 5
precision: 16 # [16, 32, 'bf16']
persistent_workers: False # default is False
profiler: 'none'
val_batch_size: 500 # validation batch size

dataloading:
  num_workers: 8  # often overriden
  prefetch_factor: 10
  persistent_workers: False  # torch default is False
  pin_memory: True

knn_eval: False
linear_eval: True
