type: 'byol'
project_name: 'byol'
dataset: 'gzmnist' # ['imagenette', 'rgz', 'gzmnist', 'gz2', 'stl10', 'cifar10']
compute: 'slurm'
seed: 69
debug: True
num_workers: 8 
prefetch_factor: 30
checkpoint_mode: 'last'
