type: 'byol'
project_name: 'byol'
dataset: 'gzmnist' # ['imagenette', 'rgz', 'gzmnist', 'gz2', 'stl10', 'cifar10']
compute: 'slurm'
seed: 69
debug: False
num_workers: 8 # per gpu
prefetch_factor: 30
checkpoint_mode: 'last'
pretraining_batch_size: 300  # max for 224 pixel images on 1 gpu