preset: 'none'

model:
    architecture: 'resnet18' 
    features: 100     # Number of encoded features (None just uses original resnet output)
    n_epochs: 100 
    downscale: False

projection_head:
    hidden: 512
    out: 128

data:
    color_channels: 3
    classes: 10
    rotate: False
    test_frac: 0.3 
    val_frac: 1
    input_height: 96
    pretrain_batch_size: 256
    val_batch_size: 500

linear:
    n_epochs: 30
    opt: 'adam'
    lr: 0.0003
    batch_size: 512
    momentum: 0
    weight_decay: 0
    scheduler: 'cosine'

optimizer:
  type: 'sgd'
  lr: 0.03
  momentum: 0.9
  weight_decay: 0.0004 # 0.0005
  lars: False
  trust_coef: 0.003

scheduler:
  type: 'cosine' # ['none', 'cosine', 'warmupcosine']
  warmup_epochs: 10  # Only used in linear warmup cosine annealing

augmentations:
  s: 0.5
  center_crop_size: 80

## AUGMENTATIONS ##
s: 0.5
center_crop_size: 80

## Optimiser ## 


## BYOL ## 
m: 0.99
m_decay: False
