preset: 'none'

model:
    architecture: 'resnet18' 
    features: 512     # Number of encoded features (null just uses original resnet output)
    n_epochs: 100 
    downscale: False

projection_head:
    hidden: 512
    out: 128

data:
    color_channels: 3
    classes: 10
    rotate: False
    input_height: 96
    pretrain_batch_size: 64

linear:
    n_epochs: 30
    opt: 'adam'
    lr: 0.0003
    batch_size: 300
    scheduler: 'cosine'
    l1_strength: 0.0
    l2_strength: 1
    n_eval_epochs: 1

optimizer:
  type: 'sgd'
  lr: 0.03
  momentum: 0.9
  weight_decay: 0.0004 # 0.0005
  lars: False
  trust_coef: 0.003

scheduler:
  type: 'cosine' # ['none', 'cosine', 'warmupcosine']
  warmup_epochs: 10  # Only used in linear warmup cosine annealing, if scheduler type is 'warmupcosine'

augmentations:
  s: 1
  center_crop_size: null


## BYOL ## 
m: 0.996
m_decay: False
